language: ruby

before_install:
  - "cp config/database.yml.travis config/database.yml"


rvm:
  - 2.3.1

gemfile:
  - Gemfile

sudo: false

services:
  - postgresql

script:
   - RAILS_ENV=test bundle exec rake db:schema:load --trace
   - bundle exec rake db:test:prepare
   - bundle exec rspec spec/

notifications:
  email: false
