language: ruby

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-4.1-stable

sudo: false

cache: bundler

before_script: "bundle update"

script: bundle exec rspec spec


notifications:
  email: false
