language: ruby

before_install:
  - "cp config/database.yml.travis config/database.yml"


rvm:
  - 2.3.1

gemfile:
  - Gemfile

sudo: false

services:
  - postgresql

script: bundle exec rspec spec

notifications:
  email: false
